################
version: '3.8' #
services:      #
################
#
####################################
 Cinnamon:                         #
  # ------------------------------ #
  image: 'dexter74/cinnamon'       #
  container_name: 'Cinnamon'       #
  restart: 'unless-stopped'        #
  # ------------------------------ #
  hostname: 'Cinnamon'             #
  # ------------------------------ #
  environment:                     #
   # ----------------------------- #
   PUID: '1000'                    #
   PGID: '1000'                    #
   # ----------------------------- #
  # ------------------------------ #
  volumes:                         #
   - 'Data:/home/marc/'            #
  # ------------------------------ #
  ports:                           #
   - '8888:8888'                   #
####################################
#
####################################
volumes:                           #
 Data:                             #
####################################
