###########################################################################
name: Docker Image CI #
#######################

###########################################################################
on:                                                                       #
  # --------------------------------------------------------------------- #
  push:                                                                   #
    branches: [ "main" ]                                                  #
  # --------------------------------------------------------------------- #
  pull_request:                                                           #
    branches: [ "main" ]                                                  #
  # --------------------------------------------------------------------- #
###########################################################################
#
#
###########################################################################
jobs:                                                                     #
  # --------------------------------------------------------------------- #
  build:                                                                  #
  # --------------------------------------------------------------------- #
    runs-on: ubuntu-latest                                                #
    # ------------------------------------------------------------------- #
    steps:                                                                #
    # ------------------------------------------------------------------- #
    - name: Checkout code                                                 #
      uses: actions/checkout@v4                                           #
    # ------------------------------------------------------------------- #
    - name: Login to Docker Hub                                           #
      uses: docker/login-action@v1                                        #
      with:                                                               #
       username: ${{ secrets.DOCKER_HUB_USERNAME }}                       #
       password: ${{ secrets.DOCKER_HUB_TOKEN }}                          #
    # ------------------------------------------------------------------- #
    - name: Build the Docker image                                        #
      run: docker build . --file Dockerfile --tag cinnamon:$(date +%s)    #
           docker push                      --tag cinnamon:$(date +%s)    #
    # ------------------------------------------------------------------- #
    #- name: Push on Docker-Hub                                           #
    # ------------------------------------------------------------------- #
  # --------------------------------------------------------------------- #
###########################################################################
