###########################################################################
name: Docker Image CI #
#######################
#
###########################################################################
on:                                                                       #
  # --------------------------------------------------------------------- #
  push:                                                                   #
    branches: [ "main" ]                                                  #
  # --------------------------------------------------------------------- #
  workflow_dispatch:                                                      #
    inputs:                                                               #
     dockerfile:                                                          #
      description: 'Path to Dockerfile'                                   #
      required: true                                                      #
      default: './Dockerfile'                                             #
###########################################################################
#
#
###########################################################################
jobs:                                                                     #
  # --------------------------------------------------------------------- #
  build:                                                                  #
  # --------------------------------------------------------------------- #
    runs-on: ubuntu-latest                                                #
    # ------------------------------------------------------------------- #
    steps:                                                                #
    -                                                                     #
     name: Checkout code                                                  #
     uses: actions/checkout@v4                                            #
    # ------------------------------------------------------------------- #
    -                                                                     #
     name: Login to Docker Hub                                            #
     uses: docker/login-action@v3                                         #
     with:                                                                #
      username: ${{ secrets.DOCKER_HUB_USERNAME }}                        #
      password: ${{ secrets.DOCKER_HUB_TOKEN }}                           #
    # ------------------------------------------------------------------- #
    -                                                                     #
     name: Build the Docker image                                         #
     run: docker build -f ${{ inputs.dockerfile }} -t cinnamon-desktop .  #
    # ------------------------------------------------------------------- #
    -                                                                     #
     name: Push the Docker image                                          #
     uses: docker/build-push-action@v6                                    #
     with:                                                                #
      push: true                                                          #
      tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cinnamon:latest            #
    # ------------------------------------------------------------------- #
###########################################################################
